### ISSUE TITLE
crypto not found

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/histoqc-dsa-plugin#1]
When I run this locally, I'm getting a javascript error about `crypto.randomUUID` not being found.  I think you need to add whatever crypto library that is to the dependencies in package.json and import it in the appropriate javascript module.  Elsewhere I've used the uuid package to do the same thing:
```
diff --git a/histoqc/web_client/js/histoqc_view.js b/histoqc/web_client/js/histoqc_view.js
index e78aa4f..9da5caa 100755
--- a/histoqc/web_client/js/histoqc_view.js
+++ b/histoqc/web_client/js/histoqc_view.js
@@ -1,5 +1,6 @@
 import { restRequest, getApiRoot } from '@girder/core/rest'

+import { v4 as uuidv4 }

 const artifact_list = [
   "thumb_small",
@@ -83,7 +84,7 @@ function initialize_table(histoqc_output_folder_id, table_id) {
         cell = document.createElement('td')
         cell.innerHTML = 'Loading ' + artifact_filename + ' ...'
         cell.style.cssText = cell_style
-        cell.id = crypto.randomUUID()
+        cell.id = uuidv4()
         row.appendChild(cell)

         load_histoqc_output_cell(cell.id, subfolder_id, artifact_filename)
diff --git a/histoqc/web_client/package.json b/histoqc/web_client/package.json
index a52ca24..98cbf37 100755
--- a/histoqc/web_client/package.json
+++ b/histoqc/web_client/package.json
@@ -8,6 +8,9 @@
     "peerDependencies": {
         "@girder/core": "*"
     },
+    "dependencies": {
+        "uuid": "^8.3.2"
+    },
     "girderPlugin": {
         "name": "histoqc",
         "main": "./main.js"
```

**Comment by robtoth** [comment]
@manthey Okay so the issue is that the crypto library that I'm using to generate a uuid is built-in (as it seems to be the proper way to do that) will only support secure hosts, a-la SSL or localhost in chromium-based browsers:

* https://stackoverflow.com/a/59533745
* https://stackoverflow.com/a/46671627
* https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features/
* https://stackoverflow.com/a/2117523

I kept it as is for best practice according to the above links, but would you recommend something different?

**Comment by manthey** [comment]
Thank you.
